# Generated by Django 4.0.4 on 2022-04-19 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_category_subcategory_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(max_length=10, verbose_name='Maxsulot soni')),
                ('price', models.PositiveIntegerField(verbose_name='Narxi')),
                ('total', models.CharField(max_length=20, verbose_name='Umumiy narxi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.product', verbose_name='Mahsulot')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
