# Generated by Django 4.0.4 on 2022-04-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
    ]
