# Generated by Django 4.0.4 on 2022-04-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.PositiveIntegerField(blank=True, verbose_name='Narxi'),
        ),
    ]
