# Generated by Django 4.0.4 on 2022-04-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='username',
            field=models.CharField(default='username', max_length=100, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
