# Generated by Django 4.0.4 on 2022-04-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_username_cart_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_id',
            field=models.CharField(max_length=100, verbose_name='User_id'),
        ),
    ]
