# Generated by Django 4.0.4 on 2022-05-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_order_remove_cart_user_id_cart_user_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Rasm'),
        ),
    ]
